imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        map_service: "@map_service"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            worlds:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name_worlds%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            worlds_pattern_service1:
                driver:   "%database_driver%"
                host:     "%database_host_service1%"
                port:     "%database_port%"
                dbname:   "%database_name_worlds%"
                user:     "%database_user_service1%"
                password: "%database_password_service1%"
                charset:  UTF8
            worlds_pattern_service2:
                driver:   "%database_driver%"
                host:     "%database_host_service2%"
                port:     "%database_port%"
                dbname:   "%database_name_worlds%"
                user:     "%database_user_service2%"
                password: "%database_password_service2%"
                charset:  UTF8
            worlds_pattern_service3:
                driver:   "%database_driver%"
                host:     "%database_host_service3%"
                port:     "%database_port%"
                dbname:   "%database_name_worlds%"
                user:     "%database_user_service3%"
                password: "%database_password_service3%"
                charset:  UTF8
            worlds_pattern_service4:
                driver:   "%database_driver%"
                host:     "%database_host_service4%"
                port:     "%database_port%"
                dbname:   "%database_name_worlds%"
                user:     "%database_user_service4%"
                password: "%database_password_service4%"
                charset:  UTF8
    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    HwsCncstatsBundle: ~
            worlds:
                connection:       worlds
                mappings:
                    HwsCncstatsBundle: ~
        auto_generate_proxy_classes: "%kernel.debug%"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: false                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

monolog:
    handlers:
        syslog:
            type: syslog
            level: warning
            ident: cncstatsweb

lsw_memcache:
    clients:
        default:
            hosts:
              - { dsn: localhost, port: 11211 }
            options:
                compression: true