parameters:
  database_driver: pdo_mysql
  database_port: null
  database_name: 
  database_name_worlds: 
  
  database_host: 
  database_user: 
  database_password: 
  
  database_host_service1: 
  database_user_service1: 
  database_password_service1: 
  database_port_service1: 3306
  
  database_host_service2: 
  database_user_service2: 
  database_password_service2: 
  database_port_service2: 3306
  
  database_host_service3: 
  database_user_service3: 
  database_password_service3: 
  database_port_service3: 3306
  
  database_host_service4: 
  database_user_service4: 
  database_password_service4: 
  database_port_service4: 3306
  
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: 
  database_path: null
